services:
  - type: web
    name: veggo-api
    env: python
    pythonVersion: 3.11.9

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: uvicorn veggo_app:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true

      - key: BASE_URL
        value: https://veggo-system.onrender.com

      - key: WAREHOUSE_LAT
        value: "40.7128"

      - key: WAREHOUSE_LNG
        value: "-74.0060"
